### ISSUE TITLE
corecmd project compile error

### ISSUE THREAD

**Issue by xb3lh1nhx** [stdware/qmsetup#12]
I wanted to test qwindowkit library, so pulled this repo as a dependency. Main README.md states that required C++ standard is 17, but I got compile error:
`qmsetup/src/corecmd/main.cpp:173:40: error: ‘std::__cxx11::string’ {aka ‘class std::__cxx11::basic_string<char>’} has no member named ‘starts_with’`

Member *starts_with* was added to a C++ 20 standard.

My version of GLIBC is `GLIBC 2.28-10`, g++ is `8.3.0-6`

Is there any chance of supporting older standards?

**Comment by xb3lh1nhx** [comment]
Replacing error with more C++ 17 friendly code results in linker errors for `filesystem` library, i.e.:

`qmsetup/src/corecmd/main.cpp:95: undefined reference to std::filesystem::__cxx11::directory_iterator::operator*() const'`

**Comment by SineStriker** [comment]
Use g++9.4 or later. The support for C++ 17 in g++ 8.x is in complete.

**Comment by xb3lh1nhx** [comment]
Thanks for the response! Sorry, upgrading g++ is not an option. Closing this issue as not related to project
